export const SELECT_ROOM = 'selectRoom'
export const WAITING_ROOM = 'waitingRoom'
export const MAKING_TEAMS = 'makingTeams'
export const TEAM_START = 'teamStart'
export const WAITING_QUESTION = 'waitingQuestion'
export const WAITING_ANSWER = 'waitingAnswer'
export const ANSWER_RESULT = 'answerResult'
export const FINAL_RESULT = 'finalResult'
